// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDuLich.Data;

#nullable disable

namespace WebDuLich.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250527172958_FixCascadeIssue")]
    partial class FixCascadeIssue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDuLich.Data.BanNhaHang", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaBan");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiBan")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("LoaiBan");

                    b.Property<string>("MaNhaHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNhaHang");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoNguoiToiDa");

                    b.HasKey("MaBan");

                    b.HasIndex("MaNhaHang");

                    b.ToTable("BANNHAHANG");
                });

            modelBuilder.Entity("WebDuLich.Data.DatBan", b =>
                {
                    b.Property<string>("MaDatBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDatBan");

                    b.Property<string>("BanNhaHangMaBan")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaBan");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayGioDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayGioDat");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("SoNguoi");

                    b.Property<int>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.Property<string>("YeuCauDacBiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YeuCauDacBiet");

                    b.HasKey("MaDatBan");

                    b.HasIndex("BanNhaHangMaBan");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DATBAN");
                });

            modelBuilder.Entity("WebDuLich.Data.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_dat_phong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Ma_nguoi_dung");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("Ma_phong");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhan_phong");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tra_phong");

                    b.Property<DateTime>("ThoiGianDat")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_dat");

                    b.Property<int>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("WebDuLich.Data.DiaDiemDuLich", b =>
                {
                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDiaDiem");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<int>("MaTinh")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaTinh");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.HasKey("MaDiaDiem");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("MaTinh");

                    b.ToTable("DIADIEMDULICH");
                });

            modelBuilder.Entity("WebDuLich.Data.GioiThieuWebsite", b =>
                {
                    b.Property<int>("IdGioiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_gioi_thieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioiThieu"));

                    b.Property<string>("IdNguoiCapNhat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_nguoi_cap_nhat");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tieu_de");

                    b.HasKey("IdGioiThieu");

                    b.HasIndex("IdNguoiCapNhat");

                    b.ToTable("GioiThieuWebsite");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhDiaDiem", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("MaDiaDiem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDiaDiem");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaDiaDiem");

                    b.ToTable("HINHANHDIADIEM");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhKhachSan", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("MaKhachSan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKS");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("HINHANHKHACHSAN");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhNhaHang", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duong_dan_anh");

                    b.Property<string>("MaNhaHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Ma_nha_hang");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaNhaHang");

                    b.ToTable("HINHANHNHAHANG");
                });

            modelBuilder.Entity("WebDuLich.Data.KhachSan", b =>
                {
                    b.Property<string>("MaKs")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKs");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DienThoai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<int>("MaTinh")
                        .HasColumnType("int")
                        .HasColumnName("Ma_tinh");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mota");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ten");

                    b.HasKey("MaKs");

                    b.HasIndex("MaTinh");

                    b.ToTable("KHACHSAN");
                });

            modelBuilder.Entity("WebDuLich.Data.Mien", b =>
                {
                    b.Property<int>("MaMien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_mien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMien"));

                    b.Property<string>("TenMien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_mien");

                    b.HasKey("MaMien");

                    b.ToTable("MIEN");
                });

            modelBuilder.Entity("WebDuLich.Data.NguoiDung", b =>
                {
                    b.Property<string>("MaTV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaND");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gioitinh");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoVaTen");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("MaTV");

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("WebDuLich.Data.NhaHang", b =>
                {
                    b.Property<string>("MaNhaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Ma_nha_hang");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("LoaiAmThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loai_am_thuc");

                    b.Property<int>("MaTinh")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("id_tinh");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten");

                    b.Property<TimeSpan>("ThoiGianDongCua")
                        .HasColumnType("time")
                        .HasColumnName("thoi_gian_dong_cua");

                    b.Property<TimeSpan>("ThoiGianMoCua")
                        .HasColumnType("time")
                        .HasColumnName("thoi_gian_mo_cua");

                    b.HasKey("MaNhaHang");

                    b.HasIndex("MaTinh");

                    b.ToTable("NhaHang");
                });

            modelBuilder.Entity("WebDuLich.Data.PhongKhachSan", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_phong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<int>("DienTich")
                        .HasColumnType("int")
                        .HasColumnName("dien_tich");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiPhong")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("loai_phong");

                    b.Property<string>("MaKhachSan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Ma_khach_san");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<string>("TienIch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tien_ich");

                    b.Property<int>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("PhongKhachSan");
                });

            modelBuilder.Entity("WebDuLich.Data.QuyenTaiKhoan", b =>
                {
                    b.Property<string>("MaQuyen")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaQuyen");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenQuyen");

                    b.HasKey("MaQuyen");

                    b.ToTable("QUYENTAIKHOAN");
                });

            modelBuilder.Entity("WebDuLich.Data.TaiKhoan", b =>
                {
                    b.Property<string>("MaTK")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTK");

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaQuyen");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("MaTK");

                    b.HasIndex("MaQuyen");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("WebDuLich.Data.Tinh", b =>
                {
                    b.Property<int>("MaTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_tinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinh"));

                    b.Property<int>("MaMien")
                        .HasColumnType("int")
                        .HasColumnName("Ma_mien");

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_tinh");

                    b.HasKey("MaTinh");

                    b.HasIndex("MaMien");

                    b.ToTable("TINH");
                });

            modelBuilder.Entity("WebDuLich.Data.BanNhaHang", b =>
                {
                    b.HasOne("WebDuLich.Data.NhaHang", "NhaHang")
                        .WithMany()
                        .HasForeignKey("MaNhaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaHang");
                });

            modelBuilder.Entity("WebDuLich.Data.DatBan", b =>
                {
                    b.HasOne("WebDuLich.Data.BanNhaHang", null)
                        .WithMany("DatBans")
                        .HasForeignKey("BanNhaHangMaBan");

                    b.HasOne("WebDuLich.Data.BanNhaHang", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebDuLich.Data.TaiKhoan", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebDuLich.Data.DatPhong", b =>
                {
                    b.HasOne("WebDuLich.Data.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDuLich.Data.PhongKhachSan", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("WebDuLich.Data.DiaDiemDuLich", b =>
                {
                    b.HasOne("WebDuLich.Data.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDuLich.Data.Tinh", "Tinh")
                        .WithMany()
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("WebDuLich.Data.GioiThieuWebsite", b =>
                {
                    b.HasOne("WebDuLich.Data.TaiKhoan", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("IdNguoiCapNhat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhDiaDiem", b =>
                {
                    b.HasOne("WebDuLich.Data.DiaDiemDuLich", "DiaDiemDuLich")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiemDuLich");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhKhachSan", b =>
                {
                    b.HasOne("WebDuLich.Data.KhachSan", "KhachSan")
                        .WithMany()
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("WebDuLich.Data.HinhAnhNhaHang", b =>
                {
                    b.HasOne("WebDuLich.Data.NhaHang", "NhaHang")
                        .WithMany()
                        .HasForeignKey("MaNhaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaHang");
                });

            modelBuilder.Entity("WebDuLich.Data.KhachSan", b =>
                {
                    b.HasOne("WebDuLich.Data.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("WebDuLich.Data.KhachSan", "MaKs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDuLich.Data.Tinh", "Tinh")
                        .WithMany("KhachSans")
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("WebDuLich.Data.NguoiDung", b =>
                {
                    b.HasOne("WebDuLich.Data.TaiKhoan", "TaiKhoan")
                        .WithOne("NguoiDung")
                        .HasForeignKey("WebDuLich.Data.NguoiDung", "MaTV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebDuLich.Data.NhaHang", b =>
                {
                    b.HasOne("WebDuLich.Data.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("WebDuLich.Data.NhaHang", "MaNhaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebDuLich.Data.Tinh", "Tinh")
                        .WithMany()
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("WebDuLich.Data.PhongKhachSan", b =>
                {
                    b.HasOne("WebDuLich.Data.KhachSan", "KhachSan")
                        .WithMany("PhongKhachSans")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("WebDuLich.Data.TaiKhoan", b =>
                {
                    b.HasOne("WebDuLich.Data.QuyenTaiKhoan", "QuyenTaiKhoan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyenTaiKhoan");
                });

            modelBuilder.Entity("WebDuLich.Data.Tinh", b =>
                {
                    b.HasOne("WebDuLich.Data.Mien", "Mien")
                        .WithMany("Tinhs")
                        .HasForeignKey("MaMien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mien");
                });

            modelBuilder.Entity("WebDuLich.Data.BanNhaHang", b =>
                {
                    b.Navigation("DatBans");
                });

            modelBuilder.Entity("WebDuLich.Data.DiaDiemDuLich", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("WebDuLich.Data.KhachSan", b =>
                {
                    b.Navigation("PhongKhachSans");
                });

            modelBuilder.Entity("WebDuLich.Data.Mien", b =>
                {
                    b.Navigation("Tinhs");
                });

            modelBuilder.Entity("WebDuLich.Data.PhongKhachSan", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("WebDuLich.Data.QuyenTaiKhoan", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("WebDuLich.Data.TaiKhoan", b =>
                {
                    b.Navigation("NguoiDung")
                        .IsRequired();
                });

            modelBuilder.Entity("WebDuLich.Data.Tinh", b =>
                {
                    b.Navigation("KhachSans");
                });
#pragma warning restore 612, 618
        }
    }
}
